In [1]:
import pandas as pd

In [3]:
data = pd.read_csv(r'C:\Users\Jona\Desktop\tuxff\data\large data\best_ball_mania_v_rd1.csv')
data.head(5)

,draft_id,user_id,username,draft_created_time,draft_filled_time,draft_time,draft_completed_time,draft_clock,draft_entry_id,tournament_entry_id,...,position_name,projection_adp,source,pick_order,overall_pick_number,team_pick_number,pick_created_time,pick_points,roster_points,made_playoffs
0,00003e5d-1f32-4ac2-9111-c705a066c881,42ed6314-26cc-4023-bbef-bcabbe77096c,millese,2024-04-29 11:04:37.973498,2024-05-27 13:50:33.218485,2024-05-27 13:51:38.902775,2024-05-27 14:42:37.125175,30,87abd2aa-bc93-4de1-813b-4162c9009430,115848af-c25b-4dde-8205-7702a5cc03db,...,QB,212.10,queue,8,209,18,2024-05-27 14:40:44.649851,52.72,1513.20,0
1,00003e5d-1f32-4ac2-9111-c705a066c881,42ed6314-26cc-4023-bbef-bcabbe77096c,millese,2024-04-29 11:04:37.973498,2024-05-27 13:50:33.218485,2024-05-27 13:51:38.902775,2024-05-27 14:42:37.125175,30,87abd2aa-bc93-4de1-813b-4162c9009430,115848af-c25b-4dde-8205-7702a5cc03db,...,WR,143.55,user,8,137,12,2024-05-27 14:24:05.023344,98.50,1513.20,0
2,00003e5d-1f32-4ac2-9111-c705a066c881,55155694-0d35-44e8-a6bc-adf67c93807f,ethan7,2024-04-29 11:04:37.973498,2024-05-27 13:50:33.218485,2024-05-27 13:51:38.902775,2024-05-27 14:42:37.125175,30,ed8c5b8e-de9a-45ac-99e0-64ac762084c3,3a135e6b-f27b-4ede-8b6c-c0bde1fe8d7c,...,TE,127.28,user,5,116,10,2024-05-27 14:18:30.936237,26.10,1234.62,0
3,00003e5d-1f32-4ac2-9111-c705a066c881,a9931249-85e2-411a-9d9b-97512cdbeb54,joeblum4,2024-04-29 11:04:37.973498,2024-05-27 13:50:33.218485,2024-05-27 13:51:38.902775,2024-05-27 14:42:37.125175,30,d4a80c89-5044-4346-9a8d-2990fb0d2e8d,0829d2f8-b8bf-445c-aef6-86b25a3cdcd3,...,RB,24.94,user,1,25,3,2024-05-27 13:56:09.561000,198.90,1557.28,0
4,00003e5d-1f32-4ac2-9111-c705a066c881,976f6af9-0cd4-476a-9dc2-d38dd162213a,eag76les,2024-04-29 11:04:37.973498,2024-05-27 13:50:33.218485,2024-05-27 13:51:38.902775,2024-05-27 14:42:37.125175,30,ee3011c0-7cf3-48dd-9500-01fa4a134ff5,ac5b08ca-e5b8-4aa7-938d-a9c0a2b608d4,...,WR,123.06,queue,6,126,11,2024-05-27 14:21:20.933368,49.50,1344.94,0